language: python
python:
    - "2.6"
    - "2.7"
install:
    - uname -a
    - sudo apt-get update -qq
    - sudo apt-get install -qq curl protobuf-compiler libprotobuf-dev libncurses5 libc6
    - sudo sh -c "curl -k https://raw.github.com/alavrik/piqi-binary/master/Linux-x86_64/piqi > /usr/bin/piqi"
    - sudo chmod +x /usr/bin/piqi
    - pip install --upgrade distribute
    - pip install --upgrade https://bitbucket.org/logilab/astroid/get/5ed6266cab78.zip
    - python setup.py build
    - python setup.py install
    - pip install -r requirements-dev.txt
script: make test && make check
